In [1]:
import pandas as pd
import numpy as np
from load_data import *
import yfinance as yf

In [2]:
start = "2022-01-10"
end = "2023-04-28"
data_nvs = get_data(['NVS'], start, end)
data_abbv = get_data(['ABBV'], start, end)
data_azn = get_data(['AZN'], start, end)
data_bmy = get_data(['BMY'], start, end)
data_jnj = get_data(['JNJ'], start, end)
data_lly = get_data(['LLY'], start, end)
data_mrk = get_data(['MRK'], start, end)
data_nvo = get_data(['NVO'], start, end)
data_pfe = get_data(['PFE'], start, end)
data_rog = get_data(['ROG'], start, end)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [3]:
data_nvs.head(5)

ticker      close  close_lag    return   volume       high  \
Date                                                                    
2022-01-18    NVS  82.362450  83.291489 -1.115407  2318300  89.839996   
2022-01-19    NVS  81.727760  82.362450 -0.770605  2044200  89.320000   
2022-01-20    NVS  81.120667  81.727760 -0.742824  2066000  89.150002   
2022-01-21    NVS  80.053642  81.120667 -1.315354  2781600  88.029999   
2022-01-24    NVS  78.305954  80.053642 -2.183147  3887800  85.129997   

                  low  rolling_var_5    target  
Date                                            
2022-01-18  89.010002      -0.938949 -1.828200  
2022-01-19  88.650002      -1.046447 -2.641527  
2022-01-20  88.139999      -1.046447 -3.462058  
2022-01-21  86.910004      -1.275365 -4.518713  
2022-01-24  83.290001      -2.009588 -6.316796

In [4]:
# dfs = [data_abbv, data_azn, data_bmy, data_jnj, data_lly, data_mrk, data_nvo, data_pfe, data_rog]
dfs = [data_nvs['target'], data_abbv['target'], data_azn['target'], data_bmy['target'], data_jnj['target'], data_lly['target'], data_mrk['target'], data_nvo['target'], data_pfe['target'], data_rog['target']]

In [5]:
covs = pd.concat(dfs, axis=1)
covs

target    target    target    target     target     target  \
Date                                                                       
2022-01-18 -1.828200 -3.655294 -0.371906 -3.067645  -5.209918  -8.751085   
2022-01-19 -2.641527 -5.699557 -1.336022 -4.525621  -4.950261 -12.042421   
2022-01-20 -3.462058 -7.654682 -2.306951 -3.921170  -4.657818 -12.165441   
2022-01-21 -4.518713 -7.634316 -3.425580 -4.320790  -4.363607 -11.665382   
2022-01-24 -6.316796 -7.712473 -6.284851 -4.994171  -4.413762 -10.256016   
...              ...       ...       ...       ...        ...        ...   
2023-04-21 -2.570955 -4.204795 -4.557931 -2.418511  -9.420443  -3.377309   
2023-04-24 -2.785363 -4.336565 -3.901360 -2.592321 -11.576554  -3.227412   
2023-04-25 -1.835710 -3.066301 -3.244789 -2.621110  -9.597240  -2.938351   
2023-04-26 -2.331278 -3.580081 -4.417002 -4.717771  -8.663146  -4.166728   
2023-04-27 -2.863216 -9.424741 -5.525381 -6.840508  -7.729052  -5.395106   

              target     target     target    target  
Date                                                  
2022-01-18 -4.111988  -8.017222  -4.695499 -0.726409  
2022-01-19 -3.783863 -10.296922  -7.368891 -0.789438  
2022-01-20 -3.540505 -12.721371  -9.215127 -0.735030  
2022-01-21 -3.613807 -14.581994  -9.615271 -0.701682  
2022-01-24 -4.146124 -13.164387 -10.150960 -0.671816  
...              ...        ...        ...       ...  
2023-04-21 -2.128847  -7.813079  -6.576231 -3.116739  
2023-04-24 -2.392976 -10.145321  -7.054904 -2.893903  
2023-04-25 -2.618794 -12.146153  -6.986451 -3.054954  
2023-04-26 -4.200277 -11.712162  -7.324162 -4.060696  
2023-04-27 -5.689957 -11.278171  -7.620930 -5.066437  

[321 rows x 10 columns]

In [6]:
new_columns = ['target_nvs', 'target_abbv', 'target_azn', 'target_bmy', 'target_jnj', 'target_lly', 'target_mrk', 'target_nvo', 'target_pfe', 'target_rog']
covs.columns = new_columns

In [26]:
from statsmodels.tsa.stattools import grangercausalitytests

def gc(df):

    gc_result = {}

    covariates = df.columns.tolist()
    covariates.pop(0)
    print(covariates)
    for i in covariates:
        # Drop any missing values
        data_subset = df[['target_nvs', i]]
        # Perform the Granger causality test
        result = grangercausalitytests(data_subset, maxlag=10, verbose=False)
        gc_result[i] = result
        #gc_result[value] = result
        
    return result



In [27]:
gc = gc(covs)
gc

['target_abbv', 'target_azn', 'target_bmy', 'target_jnj', 'target_lly', 'target_mrk', 'target_nvo', 'target_pfe', 'target_rog']


{1: ({'ssr_ftest': (5.476164060468107e-05, 0.994100274469014, 317.0, 1),
   'ssr_chi2test': (5.527988956939414e-05, 0.9940677472872785, 1),
   'lrtest': (5.527988480480417e-05, 0.9940677475429252, 1),
   'params_ftest': (5.476164059145385e-05, 0.9941002744728055, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.9051646830788592, 0.4055279989798112, 314.0, 2),
   'ssr_chi2test': (1.8391562668927137, 0.39868719840641875, 2),
   'lrtest': (1.8338748392808384, 0.3997414085164809, 2),
   'params_ftest': (0.9051646830787077, 0.40552799897986813, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.6787187104232154, 0.565631795562858, 311.0, 3),
   'ssr_chi2test': (2.0819860120377736, 0.5555657037702726, 3),
   'lrtest': (2.075200102544045, 0.5569462217817518, 3),
   'params_ftest': (0.6787187104233999, 0.5656317955627432, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0

In [12]:
covs.columns

Index(['target_nvs', 'target_abbv', 'target_azn', 'target_bmy', 'target_jnj',
       'target_lly', 'target_mrk', 'target_nvo', 'target_pfe', 'target_rog'],
      dtype='object')