In [1]:
import pandas as pd
import numpy as np
from load_data import *
import yfinance as yf

In [2]:
start = "2022-01-10"
end = "2023-04-28"
data_nvs = get_data(['NVS'], start, end)
data_abbv = get_data(['ABBV'], start, end)
data_azn = get_data(['AZN'], start, end)
data_bmy = get_data(['BMY'], start, end)
data_jnj = get_data(['JNJ'], start, end)
data_lly = get_data(['LLY'], start, end)
data_mrk = get_data(['MRK'], start, end)
data_nvo = get_data(['NVO'], start, end)
data_pfe = get_data(['PFE'], start, end)
data_rog = get_data(['ROG'], start, end)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [3]:
data_nvs.head(5)

ticker      close  close_lag    return   volume       high  \
Date                                                                    
2022-01-18    NVS  82.362442  83.291489 -1.115416  2318300  89.839996   
2022-01-19    NVS  81.727760  82.362442 -0.770596  2044200  89.320000   
2022-01-20    NVS  81.120667  81.727760 -0.742824  2066000  89.150002   
2022-01-21    NVS  80.053650  81.120667 -1.315345  2781600  88.029999   
2022-01-24    NVS  78.305954  80.053650 -2.183156  3887800  85.129997   

                  low  rolling_var_5    target  
Date                                            
2022-01-18  89.010002      -0.938959 -1.828237  
2022-01-19  88.650002      -1.046452 -2.641561  
2022-01-20  88.139999      -1.046452 -3.462090  
2022-01-21  86.910004      -1.275359 -4.518732  
2022-01-24  83.290001      -2.009594 -6.316816

In [4]:
# dfs = [data_abbv, data_azn, data_bmy, data_jnj, data_lly, data_mrk, data_nvo, data_pfe, data_rog]
dfs = [data_nvs['target'], data_abbv['target'], data_azn['target'], data_bmy['target'], data_jnj['target'], data_lly['target'], data_mrk['target'], data_nvo['target'], data_pfe['target'], data_rog['target']]

In [5]:
covs = pd.concat(dfs, axis=1)
covs

target    target    target    target     target     target  \
Date                                                                       
2022-01-18 -1.828237 -3.655301 -0.371873 -3.067641  -5.209913  -8.751097   
2022-01-19 -2.641561 -5.699590 -1.335989 -4.525593  -4.950251 -12.042424   
2022-01-20 -3.462090 -7.654713 -2.306917 -3.921144  -4.657796 -12.165456   
2022-01-21 -4.518732 -7.634352 -3.425552 -4.320767  -4.363570 -11.665386   
2022-01-24 -6.316816 -7.712514 -6.284824 -4.994150  -4.413738 -10.256003   
...              ...       ...       ...       ...        ...        ...   
2023-04-21 -2.570955 -4.204795 -4.557931 -2.418511  -9.420443  -3.377309   
2023-04-24 -2.785363 -4.336565 -3.901360 -2.592321 -11.576554  -3.227412   
2023-04-25 -1.835710 -3.066301 -3.244789 -2.621110  -9.597240  -2.938351   
2023-04-26 -2.331278 -3.580081 -4.417002 -4.717771  -8.663146  -4.166728   
2023-04-27 -2.863216 -9.424741 -5.525381 -6.840508  -7.729052  -5.395106   

              target     target     target    target  
Date                                                  
2022-01-18 -4.111988  -8.017238  -4.695481 -0.726409  
2022-01-19 -3.783863 -10.296949  -7.368870 -0.789438  
2022-01-20 -3.540497 -12.721412  -9.215102 -0.735030  
2022-01-21 -3.613813 -14.582055  -9.615248 -0.701682  
2022-01-24 -4.146126 -13.164441 -10.150947 -0.671816  
...              ...        ...        ...       ...  
2023-04-21 -2.128847  -7.813079  -6.576231 -3.116739  
2023-04-24 -2.392976 -10.145321  -7.054904 -2.893903  
2023-04-25 -2.618794 -12.146153  -6.986451 -3.054954  
2023-04-26 -4.200277 -11.712162  -7.324162 -4.060696  
2023-04-27 -5.689957 -11.278171  -7.620930 -5.066437  

[321 rows x 10 columns]

In [6]:
new_columns = ['target_nvs', 'target_abbv', 'target_azn', 'target_bmy', 'target_jnj', 'target_lly', 'target_mrk', 'target_nvo', 'target_pfe', 'target_rog']
covs.columns = new_columns

In [7]:
gc = granger_causality(covs, 'target_nvs')
gc

{1: ({'ssr_ftest': (5.475071231827073e-05, 0.994100863167208, 317.0, 1),
   'ssr_chi2test': (5.526885786071493e-05, 0.9940683392289754, 1),
   'lrtest': (5.5268853088819014e-05, 0.9940683394850396, 1),
   'params_ftest': (5.475071226311525e-05, 0.994100863171, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.9051645394735944, 0.4055280568819404, 314.0, 2),
   'ssr_chi2test': (1.8391559751087683, 0.39868725657168474, 2),
   'lrtest': (1.833874549169309, 0.3997414665012808, 2),
   'params_ftest': (0.9051645394734531, 0.40552805688199733, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.6787181171710542, 0.5656321601200172, 311.0, 3),
   'ssr_chi2test': (2.081984192222462, 0.55556607366562, 3),
   'lrtest': (2.07519829456578, 0.5569465899186816, 3),
   'params_ftest': (0.6787181171710991, 0.5656321601199888, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 