In [3]:
import pandas as pd
import numpy as np
from load_data import *
import yfinance as yf

In [4]:
start = "2022-01-10"
end = "2023-04-28"
data_nvs = get_data(['NVS'], start, end)
data_abbv = get_data(['ABBV'], start, end)
data_azn = get_data(['AZN'], start, end)
data_bmy = get_data(['BMY'], start, end)
data_jnj = get_data(['JNJ'], start, end)
data_lly = get_data(['LLY'], start, end)
data_mrk = get_data(['MRK'], start, end)
data_nvo = get_data(['NVO'], start, end)
data_pfe = get_data(['PFE'], start, end)
data_rog = get_data(['ROG'], start, end)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [5]:
data_nvs.head(5)

ticker      close  close_lag    return   volume       high  \
Date                                                                    
2022-01-18    NVS  82.362442  83.291489 -1.115416  2318300  89.839996   
2022-01-19    NVS  81.727760  82.362442 -0.770596  2044200  89.320000   
2022-01-20    NVS  81.120667  81.727760 -0.742824  2066000  89.150002   
2022-01-21    NVS  80.053650  81.120667 -1.315345  2781600  88.029999   
2022-01-24    NVS  78.305954  80.053650 -2.183156  3887800  85.129997   

                  low  rolling_var_5    target  
Date                                            
2022-01-18  89.010002      -0.938959 -1.828237  
2022-01-19  88.650002      -1.046452 -2.641561  
2022-01-20  88.139999      -1.046452 -3.462090  
2022-01-21  86.910004      -1.275359 -4.518732  
2022-01-24  83.290001      -2.009594 -6.316816

In [6]:
# dfs = [data_abbv, data_azn, data_bmy, data_jnj, data_lly, data_mrk, data_nvo, data_pfe, data_rog]
dfs = [data_nvs['target'], data_abbv['target'], data_azn['target'], data_bmy['target'], data_jnj['target'], data_lly['target'], data_mrk['target'], data_nvo['target'], data_pfe['target'], data_rog['target']]

In [7]:
covs = pd.concat(dfs, axis=1)
covs

target    target    target    target     target     target  \
Date                                                                       
2022-01-18 -1.828237 -3.655297 -0.371940 -3.067600  -5.209841  -8.751112   
2022-01-19 -2.641561 -5.699574 -1.336055 -4.525553  -4.950210 -12.042444   
2022-01-20 -3.462090 -7.654707 -2.306984 -3.921128  -4.657769 -12.165480   
2022-01-21 -4.518732 -7.634348 -3.425609 -4.320767  -4.363556 -11.665399   
2022-01-24 -6.316816 -7.712511 -6.284872 -4.994164  -4.413728 -10.256012   
...              ...       ...       ...       ...        ...        ...   
2023-04-21 -2.570955 -4.204795 -4.557931 -2.418511  -9.420443  -3.377309   
2023-04-24 -2.785363 -4.336565 -3.901360 -2.592321 -11.576554  -3.227412   
2023-04-25 -1.835710 -3.066301 -3.244789 -2.621110  -9.597240  -2.938351   
2023-04-26 -2.331278 -3.580081 -4.417002 -4.717771  -8.663146  -4.166728   
2023-04-27 -2.863216 -9.424741 -5.525381 -6.840508  -7.729052  -5.395106   

              target     target     target    target  
Date                                                  
2022-01-18 -4.111988  -8.017207  -4.695476 -0.726409  
2022-01-19 -3.783863 -10.296914  -7.368849 -0.789438  
2022-01-20 -3.540497 -12.721370  -9.215074 -0.735030  
2022-01-21 -3.613805 -14.581994  -9.615226 -0.701682  
2022-01-24 -4.146124 -13.164388 -10.150931 -0.671816  
...              ...        ...        ...       ...  
2023-04-21 -2.128847  -7.813079  -6.576223 -3.116739  
2023-04-24 -2.392976 -10.145321  -7.054897 -2.893903  
2023-04-25 -2.618794 -12.146153  -6.986442 -3.054954  
2023-04-26 -4.200277 -11.712162  -7.324155 -4.060696  
2023-04-27 -5.689957 -11.278171  -7.620927 -5.066437  

[321 rows x 10 columns]

In [8]:
new_columns = ['target_nvs', 'target_abbv', 'target_azn', 'target_bmy', 'target_jnj', 'target_lly', 'target_mrk', 'target_nvo', 'target_pfe', 'target_rog']
covs.columns = new_columns

In [9]:
gc = granger_causality(covs, 'target_nvs')
gc


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.7694  , p=0.1844  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=1.7862  , p=0.1814  , df=1
likelihood ratio test: chi2=1.7812  , p=0.1820  , df=1
parameter F test:         F=1.7694  , p=0.1844  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.3815  , p=0.2527  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=2.8069  , p=0.2457  , df=2
likelihood ratio test: chi2=2.7947  , p=0.2473  , df=2
parameter F test:         F=1.3815  , p=0.2527  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.3253  , p=0.2662  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=4.0653  , p=0.2545  , df=3
likelihood ratio test: chi2=4.0395  , p=0.2572  , df=3
parameter F test:         F=1.3253  , p=0.2662  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.2269  , p=0.0660  

{1: ({'ssr_ftest': (5.475071231827073e-05, 0.994100863167208, 317.0, 1),
   'ssr_chi2test': (5.526885786071493e-05, 0.9940683392289754, 1),
   'lrtest': (5.5268853088819014e-05, 0.9940683394850396, 1),
   'params_ftest': (5.475071226311525e-05, 0.994100863171, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.9051645394735944, 0.4055280568819404, 314.0, 2),
   'ssr_chi2test': (1.8391559751087683, 0.39868725657168474, 2),
   'lrtest': (1.833874549169309, 0.3997414665012808, 2),
   'params_ftest': (0.9051645394734531, 0.40552805688199733, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.6787181171710542, 0.5656321601200172, 311.0, 3),
   'ssr_chi2test': (2.081984192222462, 0.55556607366562, 3),
   'lrtest': (2.07519829456578, 0.5569465899186816, 3),
   'params_ftest': (0.6787181171710991, 0.5656321601199888, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 

In [10]:
# visualisation = pd.DataFrame.from_dict(gc, orient='index')
# visualisation

In [11]:
gc[1]

({'ssr_ftest': (5.475071231827073e-05, 0.994100863167208, 317.0, 1),
  'ssr_chi2test': (5.526885786071493e-05, 0.9940683392289754, 1),
  'lrtest': (5.5268853088819014e-05, 0.9940683394850396, 1),
  'params_ftest': (5.475071226311525e-05, 0.994100863171, 317.0, 1.0)},
  array([[0., 1., 0.]])])

In [12]:
nvs_abbv = [data_nvs['target'], data_abbv['target']]
granger_abbv = pd.concat(nvs_abbv, axis=1)
columns=['NVS', 'ABBV']
granger_abbv.colums = new_columns
#granger_abbv

C:\Users\HP\AppData\Local\Temp\ipykernel_7200\1641691575.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_abbv.colums = new_columns


In [13]:
nvs_azn = [data_nvs['target'], data_azn['target']]
granger_azn = pd.concat(nvs_azn, axis=1)
columns=['NVS', 'AZN']
granger_azn.colums = new_columns

C:\Users\HP\AppData\Local\Temp\ipykernel_7200\3358772045.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_azn.colums = new_columns


In [14]:
grangercausalitytests(granger_azn, 5,verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0761  , p=0.7829  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=0.0768  , p=0.7817  , df=1
likelihood ratio test: chi2=0.0768  , p=0.7817  , df=1
parameter F test:         F=0.0761  , p=0.7829  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.4880  , p=0.6143  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=0.9915  , p=0.6091  , df=2
likelihood ratio test: chi2=0.9900  , p=0.6096  , df=2
parameter F test:         F=0.4880  , p=0.6143  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.7752  , p=0.0415  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=8.5130  , p=0.0365  , df=3
likelihood ratio test: chi2=8.4010  , p=0.0384  , df=3
parameter F test:         F=2.7752  , p=0.0415  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=3.5605  , p=0.0074  

{1: ({'ssr_ftest': (0.07607240282153628, 0.7828719777308726, 317.0, 1),
   'ssr_chi2test': (0.0767923309239483, 0.7816923478522354, 1),
   'lrtest': (0.07678311823826789, 0.7817051115401982, 1),
   'params_ftest': (0.07607240282151738, 0.7828719777308726, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.48798423517073575, 0.6143272996321465, 314.0, 2),
   'ssr_chi2test': (0.9915093695507305, 0.6091110469596906, 2),
   'lrtest': (0.9899716603270008, 0.6095795448775969, 2),
   'params_ftest': (0.4879842351707171, 0.6143272996321465, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (2.775198917125235, 0.04150358863199188, 311.0, 3),
   'ssr_chi2test': (8.51298960430056, 0.03651822278896024, 3),
   'lrtest': (8.401035153048383, 0.038411374891670465, 3),
   'params_ftest': (2.7751989171251785, 0.04150358863199508, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0.,

In [15]:
nvs_bmy = [data_nvs['target'], data_bmy['target']]
granger_bmy = pd.concat(nvs_bmy, axis=1)
columns=['NVS', 'BMY']
granger_bmy.colums = new_columns

C:\Users\HP\AppData\Local\Temp\ipykernel_7200\3223664691.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_bmy.colums = new_columns


In [16]:
grangercausalitytests(granger_bmy, 5,verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.7969  , p=0.3727  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=0.8044  , p=0.3698  , df=1
likelihood ratio test: chi2=0.8034  , p=0.3701  , df=1
parameter F test:         F=0.7969  , p=0.3727  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.7189  , p=0.4881  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=1.4607  , p=0.4817  , df=2
likelihood ratio test: chi2=1.4574  , p=0.4825  , df=2
parameter F test:         F=0.7189  , p=0.4881  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.1558  , p=0.0932  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=6.6130  , p=0.0853  , df=3
likelihood ratio test: chi2=6.5451  , p=0.0879  , df=3
parameter F test:         F=2.1558  , p=0.0932  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.4433  , p=0.0467  

{1: ({'ssr_ftest': (0.7968804791437395, 0.3727048384872719, 317.0, 1),
   'ssr_chi2test': (0.8044219347823238, 0.36977456349207916, 1),
   'lrtest': (0.8034125406616113, 0.37007503050086077, 1),
   'params_ftest': (0.7968804791437283, 0.3727048384872719, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.7189051141846651, 0.4880857441158356, 314.0, 2),
   'ssr_chi2test': (1.460705295700052, 0.48173907588263987, 2),
   'lrtest': (1.4573711752046847, 0.4825428337160229, 2),
   'params_ftest': (0.7189051141846876, 0.4880857441158356, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (2.155800515908208, 0.09322567935403081, 311.0, 3),
   'ssr_chi2test': (6.612970071306849, 0.08531214446788846, 3),
   'lrtest': (6.545148692167345, 0.08789885597533596, 3),
   'params_ftest': (2.155800515908292, 0.09322567935402255, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0.

In [17]:
nvs_jnj = [data_nvs['target'], data_jnj['target']]
granger_jnj = pd.concat(nvs_jnj, axis=1)
columns=['NVS', 'JNJ']
granger_jnj.colums = new_columns
grangercausalitytests(granger_jnj, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=3.9190  , p=0.0486  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=3.9561  , p=0.0467  , df=1
likelihood ratio test: chi2=3.9318  , p=0.0474  , df=1
parameter F test:         F=3.9190  , p=0.0486  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0039  , p=0.9961  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=0.0079  , p=0.9960  , df=2
likelihood ratio test: chi2=0.0079  , p=0.9960  , df=2
parameter F test:         F=0.0039  , p=0.9961  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.0399  , p=0.9893  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=0.1225  , p=0.9890  , df=3
likelihood ratio test: chi2=0.1225  , p=0.9890  , df=3
parameter F test:         F=0.0399  , p=0.9893  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.9002  , p=0.4641  

C:\Users\HP\AppData\Local\Temp\ipykernel_7200\1911824464.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_jnj.colums = new_columns


{1: ({'ssr_ftest': (3.918980040060019, 0.04860853754842146, 317.0, 1),
   'ssr_chi2test': (3.9560681792403978, 0.04670266860330047, 1),
   'lrtest': (3.9318140050380634, 0.04738080951525799, 1),
   'params_ftest': (3.918980040059932, 0.048608537548424494, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.0038964541530555332, 0.996111175337099, 314.0, 2),
   'ssr_chi2test': (0.007916999202705192, 0.996049324930321, 2),
   'lrtest': (0.007916900961618012, 0.9960493738568065, 2),
   'params_ftest': (0.003896454153089254, 0.9961111753370643, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.03994612172280803, 0.9893328034289122, 311.0, 3),
   'ssr_chi2test': (0.12253569171562333, 0.9890022526509105, 3),
   'lrtest': (0.12251208929467339, 0.9890053527193506, 3),
   'params_ftest': (0.039946121722782106, 0.9893328034289257, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
        

In [18]:
nvs_lly = [data_nvs['target'], data_lly['target']]
granger_lly = pd.concat(nvs_lly, axis=1)
columns=['NVS', 'JNJ']
granger_lly.colums = new_columns
grangercausalitytests(granger_lly, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=7.3639  , p=0.0070  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=7.4336  , p=0.0064  , df=1
likelihood ratio test: chi2=7.3486  , p=0.0067  , df=1
parameter F test:         F=7.3639  , p=0.0070  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.8796  , p=0.4160  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=1.7872  , p=0.4092  , df=2
likelihood ratio test: chi2=1.7822  , p=0.4102  , df=2
parameter F test:         F=0.8796  , p=0.4160  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.8978  , p=0.1299  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=5.8215  , p=0.1206  , df=3
likelihood ratio test: chi2=5.7689  , p=0.1234  , df=3
parameter F test:         F=1.8978  , p=0.1299  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=4.0804  , p=0.0031  

C:\Users\HP\AppData\Local\Temp\ipykernel_7200\3817913441.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_lly.colums = new_columns


{1: ({'ssr_ftest': (7.363895663563719, 0.007018551923445063, 317.0, 1),
   'ssr_chi2test': (7.433585527887666, 0.006401766173306498, 1),
   'lrtest': (7.348558859244918, 0.006711653577457756, 1),
   'params_ftest': (7.363895663563453, 0.007018551923446222, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.8796079030022548, 0.41596547161778286, 314.0, 2),
   'ssr_chi2test': (1.7872287965459825, 0.40917415845768, 2),
   'lrtest': (1.782240855821101, 0.41019590024923, 2),
   'params_ftest': (0.8796079030021825, 0.41596547161781205, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (1.897791333356599, 0.12988475275507996, 311.0, 3),
   'ssr_chi2test': (5.821520681743394, 0.12062397602384224, 3),
   'lrtest': (5.768875886043816, 0.12341263995727365, 3),
   'params_ftest': (1.8977913333566194, 0.12988475275507766, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0.

In [19]:
nvs_mrk = [data_nvs['target'], data_mrk['target']]
granger_mkr = pd.concat(nvs_mrk, axis=1)
columns=['NVS', 'MRK']
granger_mkr.colums = new_columns
grangercausalitytests(granger_mkr, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.3076  , p=0.5795  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=0.3105  , p=0.5774  , df=1
likelihood ratio test: chi2=0.3104  , p=0.5774  , df=1
parameter F test:         F=0.3076  , p=0.5795  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0602  , p=0.9416  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=0.1224  , p=0.9406  , df=2
likelihood ratio test: chi2=0.1224  , p=0.9407  , df=2
parameter F test:         F=0.0602  , p=0.9416  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.9714  , p=0.4065  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=2.9798  , p=0.3948  , df=3
likelihood ratio test: chi2=2.9659  , p=0.3969  , df=3
parameter F test:         F=0.9714  , p=0.4065  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.3250  , p=0.2605  

C:\Users\HP\AppData\Local\Temp\ipykernel_7200\1741930676.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_mkr.colums = new_columns


{1: ({'ssr_ftest': (0.3076216126337511, 0.5795344396604493, 317.0, 1),
   'ssr_chi2test': (0.3105328581791809, 0.5773533862353709, 1),
   'lrtest': (0.3103822826851683, 0.5774456961255692, 1),
   'params_ftest': (0.307621612633768, 0.5795344396604059, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.06023098970140059, 0.941557896162768, 314.0, 2),
   'ssr_chi2test': (0.12238016378819612, 0.9406444233080065, 2),
   'lrtest': (0.12235669501831126, 0.9406554612565252, 2),
   'params_ftest': (0.06023098970133427, 0.9415578961628501, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.9714002465378719, 0.4064600208030238, 311.0, 3),
   'ssr_chi2test': (2.979793682305884, 0.3947510965652373, 3),
   'lrtest': (2.9659193275884945, 0.39690964814902296, 3),
   'params_ftest': (0.9714002465378254, 0.40646002080304533, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0

In [20]:
nvs_nvo = [data_nvs['target'], data_nvo['target']]
granger_nvo = pd.concat(nvs_nvo, axis=1)
columns=['NVS', 'NVO']
granger_nvo.colums = new_columns
grangercausalitytests(granger_nvo, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=6.3309  , p=0.0124  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=6.3908  , p=0.0115  , df=1
likelihood ratio test: chi2=6.3278  , p=0.0119  , df=1
parameter F test:         F=6.3309  , p=0.0124  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.6719  , p=0.0707  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=5.4289  , p=0.0662  , df=2
likelihood ratio test: chi2=5.3832  , p=0.0678  , df=2
parameter F test:         F=2.6719  , p=0.0707  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.8761  , p=0.1335  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=5.7549  , p=0.1242  , df=3
likelihood ratio test: chi2=5.7034  , p=0.1270  , df=3
parameter F test:         F=1.8761  , p=0.1335  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.8265  , p=0.1235  

C:\Users\HP\AppData\Local\Temp\ipykernel_7200\2682914152.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_nvo.colums = new_columns


{1: ({'ssr_ftest': (6.330890395600085, 0.012358914006399485, 317.0, 1),
   'ssr_chi2test': (6.390804184832893, 0.011471304755955727, 1),
   'lrtest': (6.327825102710335, 0.011885799019300201, 1),
   'params_ftest': (6.330890395600005, 0.012358914006399904, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (2.6718919534107792, 0.0706928413084627, 314.0, 2),
   'ssr_chi2test': (5.428876007248653, 0.06624217040775741, 2),
   'lrtest': (5.383198076770668, 0.06777248188102868, 2),
   'params_ftest': (2.6718919534091468, 0.07069284130857614, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (1.8760694316384323, 0.13353650801436776, 311.0, 3),
   'ssr_chi2test': (5.754888224382844, 0.12416384955327235, 3),
   'lrtest': (5.703434584526349, 0.12696481361126027, 3),
   'params_ftest': (1.8760694316385447, 0.1335365080143489, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0.

In [21]:
nvs_pfe = [data_nvs['target'], data_pfe['target']]
granger_pfe = pd.concat(nvs_pfe, axis=1)
columns=['NVS', 'PFE']
granger_pfe.colums = new_columns
grangercausalitytests(granger_pfe, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.6327  , p=0.4269  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=0.6387  , p=0.4242  , df=1
likelihood ratio test: chi2=0.6381  , p=0.4244  , df=1
parameter F test:         F=0.6327  , p=0.4269  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.2050  , p=0.8148  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=0.4165  , p=0.8120  , df=2
likelihood ratio test: chi2=0.4162  , p=0.8121  , df=2
parameter F test:         F=0.2050  , p=0.8148  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.3429  , p=0.7943  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=1.0519  , p=0.7887  , df=3
likelihood ratio test: chi2=1.0502  , p=0.7891  , df=3
parameter F test:         F=0.3429  , p=0.7943  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.1151  , p=0.0788  

C:\Users\HP\AppData\Local\Temp\ipykernel_7200\1091317770.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_pfe.colums = new_columns


{1: ({'ssr_ftest': (0.6327420451679923, 0.42694649859720457, 317.0, 1),
   'ssr_chi2test': (0.6387301402326735, 0.4241710061578916, 1),
   'lrtest': (0.6380935244286547, 0.4244020038659595, 1),
   'params_ftest': (0.6327420451679711, 0.42694649859723044, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.20496704658137616, 0.8147830737396768, 314.0, 2),
   'ssr_chi2test': (0.41646170611120376, 0.8120195578765963, 2),
   'lrtest': (0.41619009240173455, 0.8121298431873156, 2),
   'params_ftest': (0.2049670465814187, 0.8147830737396342, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.34291579704069125, 0.7943083036674153, 311.0, 3),
   'ssr_chi2test': (1.0519024770958825, 0.7886958247426238, 3),
   'lrtest': (1.050166526220778, 0.7891156095496217, 3),
   'params_ftest': (0.34291579704067926, 0.7943083036674321, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0.

In [22]:
nvs_rog = [data_nvs['target'], data_rog['target']]
granger_rog = pd.concat(nvs_rog, axis=1)
columns=['NVS', 'ROG']
granger_rog.colums = new_columns
grangercausalitytests(granger_rog, 5, verbose=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_7200\3048451869.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_rog.colums = new_columns



Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0001  , p=0.9941  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=0.0001  , p=0.9941  , df=1
likelihood ratio test: chi2=0.0001  , p=0.9941  , df=1
parameter F test:         F=0.0001  , p=0.9941  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.9052  , p=0.4055  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=1.8392  , p=0.3987  , df=2
likelihood ratio test: chi2=1.8339  , p=0.3997  , df=2
parameter F test:         F=0.9052  , p=0.4055  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.6787  , p=0.5656  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=2.0820  , p=0.5556  , df=3
likelihood ratio test: chi2=2.0752  , p=0.5569  , df=3
parameter F test:         F=0.6787  , p=0.5656  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.1729  , p=0.3227  

{1: ({'ssr_ftest': (5.475071231827073e-05, 0.994100863167208, 317.0, 1),
   'ssr_chi2test': (5.526885786071493e-05, 0.9940683392289754, 1),
   'lrtest': (5.5268853088819014e-05, 0.9940683394850396, 1),
   'params_ftest': (5.475071226311525e-05, 0.994100863171, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.9051645394735944, 0.4055280568819404, 314.0, 2),
   'ssr_chi2test': (1.8391559751087683, 0.39868725657168474, 2),
   'lrtest': (1.833874549169309, 0.3997414665012808, 2),
   'params_ftest': (0.9051645394734531, 0.40552805688199733, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.6787181171710542, 0.5656321601200172, 311.0, 3),
   'ssr_chi2test': (2.081984192222462, 0.55556607366562, 3),
   'lrtest': (2.07519829456578, 0.5569465899186816, 3),
   'params_ftest': (0.6787181171710991, 0.5656321601199888, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 

In [23]:
start = "2022-01-01"
end = "2023-05-01"
t = ['NVS', 'JNJ', 'LLY', 'NVO']

deep_ar_2 = get_data(t, start, end)
deep_ar_2

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


ticker       close   close_lag    return   volume        high  \
Date                                                                       
2022-01-10    NVS   82.859161   82.150887  0.862163  2753400   90.129997   
2022-01-11    NVS   82.666000   82.859161 -0.233120  2104100   89.959999   
2022-01-12    NVS   82.592407   82.666000 -0.089025  2205100   89.849998   
2022-01-13    NVS   83.355873   82.592407  0.924378  1864600   90.989998   
2022-01-14    NVS   83.291489   83.355873 -0.077240  1576200   90.860001   
...           ...         ...         ...       ...      ...         ...   
2023-04-24    NVO  170.479996  172.649994 -1.256877  1188200  171.419998   
2023-04-25    NVO  168.580002  170.479996 -1.114497  1117300  170.869995   
2023-04-26    NVO  164.990005  168.580002 -2.129551  1121400  165.770004   
2023-04-27    NVO  166.020004  164.990005  0.624279  1153800  166.240005   
2023-04-28    NVO  167.089996  166.020004  0.644496  1118800  168.089996   

                   low  rolling_var_5     target  
Date                                              
2022-01-10   88.459999      -0.305110  -1.883599  
2022-01-11   89.290001      -0.127425  -1.555797  
2022-01-12   89.169998      -0.204301  -1.359644  
2022-01-13   90.120003      -0.204301  -1.183776  
2022-01-14   90.139999      -0.204301  -1.045437  
...                ...            ...        ...  
2023-04-24  169.729996      -2.489566 -10.145321  
2023-04-25  168.199997      -2.489566 -12.146153  
2023-04-26  163.470001      -1.955016 -11.712162  
2023-04-27  164.449997      -1.955016 -11.278171  
2023-04-28  165.570007      -1.955016 -10.844180  

[1308 rows x 9 columns]

In [24]:
deep_ar_2.to_csv("dar_data2.csv")

In [25]:
t3 = ['NVS', 'ABBV', 'AZN', 'BMY', 'JNJ', 'LLY', 'MRK', 'NVO', 'PFE', 'ROG']

deep_ar_3 = get_data(t3, start, end)
deep_ar_3

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


ticker       close   close_lag    return   volume        high  \
Date                                                                       
2022-01-10    NVS   82.859161   82.150887  0.862163  2753400   90.129997   
2022-01-11    NVS   82.666000   82.859161 -0.233120  2104100   89.959999   
2022-01-12    NVS   82.592407   82.666000 -0.089025  2205100   89.849998   
2022-01-13    NVS   83.355873   82.592407  0.924378  1864600   90.989998   
2022-01-14    NVS   83.291489   83.355873 -0.077240  1576200   90.860001   
...           ...         ...         ...       ...      ...         ...   
2023-04-24    ROG  158.729996  158.979996 -0.157252    85700  159.199997   
2023-04-25    ROG  157.229996  158.729996 -0.945001   143300  158.550003   
2023-04-26    ROG  154.539993  157.229996 -1.710871   139900  157.320007   
2023-04-27    ROG  155.600006  154.539993  0.685915   106100  156.270004   
2023-04-28    ROG  160.949997  155.600006  3.438297   305800  167.039993   

                   low  rolling_var_5    target  
Date                                             
2022-01-10   88.459999      -0.305110 -1.883599  
2022-01-11   89.290001      -0.127425 -1.555797  
2022-01-12   89.169998      -0.204301 -1.359644  
2022-01-13   90.120003      -0.204301 -1.183776  
2022-01-14   90.139999      -0.204301 -1.045437  
...                ...            ...       ...  
2023-04-24  158.009995      -0.542235 -2.893903  
2023-04-25  156.309998      -0.866573 -3.054954  
2023-04-26  154.110001      -1.557697 -4.060696  
2023-04-27  153.449997      -1.557697 -5.066437  
2023-04-28  158.570007      -1.557697 -6.081899  

[3270 rows x 9 columns]

In [26]:
deep_ar_3.to_csv("dar_data3.csv")