In [1]:
import pandas as pd
import numpy as np
from load_data import *
import yfinance as yf

In [2]:
start = "2022-01-10"
end = "2023-04-28"
data_nvs = get_data(['NVS'], start, end)
data_abbv = get_data(['ABBV'], start, end)
data_azn = get_data(['AZN'], start, end)
data_bmy = get_data(['BMY'], start, end)
data_jnj = get_data(['JNJ'], start, end)
data_lly = get_data(['LLY'], start, end)
data_mrk = get_data(['MRK'], start, end)
data_nvo = get_data(['NVO'], start, end)
data_pfe = get_data(['PFE'], start, end)
data_rog = get_data(['ROG'], start, end)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [3]:
data_nvs.head(5)

ticker      close  close_lag    return   volume       high  \
Date                                                                    
2022-01-18    NVS  82.362442  83.291489 -1.115416  2318300  89.839996   
2022-01-19    NVS  81.727760  82.362442 -0.770596  2044200  89.320000   
2022-01-20    NVS  81.120667  81.727760 -0.742824  2066000  89.150002   
2022-01-21    NVS  80.053650  81.120667 -1.315345  2781600  88.029999   
2022-01-24    NVS  78.305954  80.053650 -2.183156  3887800  85.129997   

                  low  rolling_var_5    target  
Date                                            
2022-01-18  89.010002      -0.938959 -1.828237  
2022-01-19  88.650002      -1.046452 -2.641561  
2022-01-20  88.139999      -1.046452 -3.462090  
2022-01-21  86.910004      -1.275359 -4.518732  
2022-01-24  83.290001      -2.009594 -6.316816

In [4]:
# dfs = [data_abbv, data_azn, data_bmy, data_jnj, data_lly, data_mrk, data_nvo, data_pfe, data_rog]
dfs = [data_nvs['target'], data_abbv['target'], data_azn['target'], data_bmy['target'], data_jnj['target'], data_lly['target'], data_mrk['target'], data_nvo['target'], data_pfe['target'], data_rog['target']]

In [5]:
covs = pd.concat(dfs, axis=1)
covs

target    target    target    target     target     target  \
Date                                                                       
2022-01-18 -1.828237 -3.655292 -0.371873 -3.067660  -5.209918  -8.751072   
2022-01-19 -2.641561 -5.699534 -1.335989 -4.525647  -4.950261 -12.042423   
2022-01-20 -3.462090 -7.654659 -2.306917 -3.921193  -4.657811 -12.165457   
2022-01-21 -4.518732 -7.634317 -3.425557 -4.320814  -4.363591 -11.665389   
2022-01-24 -6.316816 -7.712498 -6.284836 -4.994196  -4.413743 -10.256015   
...              ...       ...       ...       ...        ...        ...   
2023-04-21 -2.570955 -4.204795 -4.557931 -2.418511  -9.420443  -3.377309   
2023-04-24 -2.785363 -4.336565 -3.901360 -2.592321 -11.576554  -3.227412   
2023-04-25 -1.835710 -3.066301 -3.244789 -2.621110  -9.597240  -2.938351   
2023-04-26 -2.331278 -3.580081 -4.417002 -4.717771  -8.663146  -4.166728   
2023-04-27 -2.863216 -9.424741 -5.525381 -6.840508  -7.729052  -5.395106   

              target     target     target    target  
Date                                                  
2022-01-18 -4.111945  -8.017222  -4.695485 -0.726409  
2022-01-19 -3.783827 -10.296922  -7.368870 -0.789438  
2022-01-20 -3.540469 -12.721371  -9.215090 -0.735030  
2022-01-21 -3.613793 -14.581994  -9.615243 -0.701682  
2022-01-24 -4.146115 -13.164387 -10.150950 -0.671816  
...              ...        ...        ...       ...  
2023-04-21 -2.128847  -7.813079  -6.576231 -3.116739  
2023-04-24 -2.392976 -10.145321  -7.054904 -2.893903  
2023-04-25 -2.618794 -12.146153  -6.986451 -3.054954  
2023-04-26 -4.200277 -11.712162  -7.324162 -4.060696  
2023-04-27 -5.689957 -11.278171  -7.620930 -5.066437  

[321 rows x 10 columns]

In [6]:
new_columns = ['target_nvs', 'target_abbv', 'target_azn', 'target_bmy', 'target_jnj', 'target_lly', 'target_mrk', 'target_nvo', 'target_pfe', 'target_rog']
covs.columns = new_columns

In [7]:
gc = granger_causality(covs, 'target_nvs')
gc


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.7694  , p=0.1844  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=1.7862  , p=0.1814  , df=1
likelihood ratio test: chi2=1.7812  , p=0.1820  , df=1
parameter F test:         F=1.7694  , p=0.1844  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.3815  , p=0.2527  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=2.8069  , p=0.2457  , df=2
likelihood ratio test: chi2=2.7947  , p=0.2473  , df=2
parameter F test:         F=1.3815  , p=0.2527  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.3252  , p=0.2662  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=4.0652  , p=0.2545  , df=3
likelihood ratio test: chi2=4.0394  , p=0.2572  , df=3
parameter F test:         F=1.3252  , p=0.2662  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.2269  , p=0.0660  

{1: ({'ssr_ftest': (5.475071231827073e-05, 0.994100863167208, 317.0, 1),
   'ssr_chi2test': (5.526885786071493e-05, 0.9940683392289754, 1),
   'lrtest': (5.5268853088819014e-05, 0.9940683394850396, 1),
   'params_ftest': (5.475071226311525e-05, 0.994100863171, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.9051645394735944, 0.4055280568819404, 314.0, 2),
   'ssr_chi2test': (1.8391559751087683, 0.39868725657168474, 2),
   'lrtest': (1.833874549169309, 0.3997414665012808, 2),
   'params_ftest': (0.9051645394734531, 0.40552805688199733, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.6787181171710542, 0.5656321601200172, 311.0, 3),
   'ssr_chi2test': (2.081984192222462, 0.55556607366562, 3),
   'lrtest': (2.07519829456578, 0.5569465899186816, 3),
   'params_ftest': (0.6787181171710991, 0.5656321601199888, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 

In [8]:
# visualisation = pd.DataFrame.from_dict(gc, orient='index')
# visualisation

In [9]:
gc[1]

({'ssr_ftest': (5.475071231827073e-05, 0.994100863167208, 317.0, 1),
  'ssr_chi2test': (5.526885786071493e-05, 0.9940683392289754, 1),
  'lrtest': (5.5268853088819014e-05, 0.9940683394850396, 1),
  'params_ftest': (5.475071226311525e-05, 0.994100863171, 317.0, 1.0)},
  array([[0., 1., 0.]])])

In [10]:
nvs_abbv = [data_nvs['target'], data_abbv['target']]
granger_abbv = pd.concat(nvs_abbv, axis=1)
columns=['NVS', 'ABBV']
granger_abbv.colums = new_columns
#granger_abbv

C:\Users\HP\AppData\Local\Temp\ipykernel_8708\3092057338.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_abbv.colums = new_columns


target    target
Date                          
2022-01-18 -1.828237 -3.655292
2022-01-19 -2.641561 -5.699534
2022-01-20 -3.462090 -7.654659
2022-01-21 -4.518732 -7.634317
2022-01-24 -6.316816 -7.712498
...              ...       ...
2023-04-21 -2.570955 -4.204795
2023-04-24 -2.785363 -4.336565
2023-04-25 -1.835710 -3.066301
2023-04-26 -2.331278 -3.580081
2023-04-27 -2.863216 -9.424741

[321 rows x 2 columns]

In [11]:
nvs_azn = [data_nvs['target'], data_azn['target']]
granger_azn = pd.concat(nvs_azn, axis=1)
columns=['NVS', 'AZN']
granger_azn.colums = new_columns

C:\Users\HP\AppData\Local\Temp\ipykernel_8708\3358772045.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_azn.colums = new_columns


In [13]:
grangercausalitytests(granger_azn, 5,verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0761  , p=0.7829  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=0.0768  , p=0.7817  , df=1
likelihood ratio test: chi2=0.0768  , p=0.7817  , df=1
parameter F test:         F=0.0761  , p=0.7829  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.4880  , p=0.6143  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=0.9915  , p=0.6091  , df=2
likelihood ratio test: chi2=0.9900  , p=0.6096  , df=2
parameter F test:         F=0.4880  , p=0.6143  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.7752  , p=0.0415  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=8.5130  , p=0.0365  , df=3
likelihood ratio test: chi2=8.4010  , p=0.0384  , df=3
parameter F test:         F=2.7752  , p=0.0415  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=3.5605  , p=0.0074  

{1: ({'ssr_ftest': (0.07606986556069659, 0.7828755075624292, 317.0, 1),
   'ssr_chi2test': (0.07678976965117637, 0.7816958962772328, 1),
   'lrtest': (0.07678055758003666, 0.7817086593429583, 1),
   'params_ftest': (0.07606986556066221, 0.7828755075624292, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.48798389733100234, 0.6143275065332672, 314.0, 2),
   'ssr_chi2test': (0.9915086831120365, 0.6091112560184224, 2),
   'lrtest': (0.9899709760153428, 0.6095797534488272, 2),
   'params_ftest': (0.4879838973310075, 0.6143275065332457, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (2.7752028443780605, 0.041503373820782646, 311.0, 3),
   'ssr_chi2test': (8.51300165124331, 0.036518024062999775, 3),
   'lrtest': (8.401046885897813, 0.03841117155428395, 3),
   'params_ftest': (2.7752028443779593, 0.04150337382078825, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 

In [14]:
nvs_bmy = [data_nvs['target'], data_bmy['target']]
granger_bmy = pd.concat(nvs_bmy, axis=1)
columns=['NVS', 'BMY']
granger_bmy.colums = new_columns

C:\Users\HP\AppData\Local\Temp\ipykernel_8708\3223664691.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_bmy.colums = new_columns


In [15]:
grangercausalitytests(granger_bmy, 5,verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.7969  , p=0.3727  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=0.8044  , p=0.3698  , df=1
likelihood ratio test: chi2=0.8034  , p=0.3701  , df=1
parameter F test:         F=0.7969  , p=0.3727  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.7189  , p=0.4881  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=1.4607  , p=0.4817  , df=2
likelihood ratio test: chi2=1.4574  , p=0.4825  , df=2
parameter F test:         F=0.7189  , p=0.4881  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.1558  , p=0.0932  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=6.6129  , p=0.0853  , df=3
likelihood ratio test: chi2=6.5451  , p=0.0879  , df=3
parameter F test:         F=2.1558  , p=0.0932  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.4432  , p=0.0467  

{1: ({'ssr_ftest': (0.7968812172052517, 0.3727046173841516, 317.0, 1),
   'ssr_chi2test': (0.8044226798286452, 0.3697743418392888, 1),
   'lrtest': (0.8034132838396317, 0.37007480915336066, 1),
   'params_ftest': (0.7968812172052447, 0.3727046173841516, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.7188956772317069, 0.4880903291847345, 314.0, 2),
   'ssr_chi2test': (1.4606861212542326, 0.48174369444468423, 2),
   'lrtest': (1.4573520881581317, 0.4825474388967633, 2),
   'params_ftest': (0.7188956772316983, 0.4880903291847345, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (2.1557806690914987, 0.09322807131504893, 311.0, 3),
   'ssr_chi2test': (6.612909190717972, 0.08531443325075648, 3),
   'lrtest': (6.545089051823425, 0.08790116354313296, 3),
   'params_ftest': (2.1557806690915147, 0.09322807131504775, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 

In [16]:
nvs_jnj = [data_nvs['target'], data_jnj['target']]
granger_jnj = pd.concat(nvs_jnj, axis=1)
columns=['NVS', 'JNJ']
granger_jnj.colums = new_columns
grangercausalitytests(granger_jnj, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=3.9190  , p=0.0486  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=3.9561  , p=0.0467  , df=1
likelihood ratio test: chi2=3.9319  , p=0.0474  , df=1
parameter F test:         F=3.9190  , p=0.0486  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0039  , p=0.9961  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=0.0079  , p=0.9960  , df=2
likelihood ratio test: chi2=0.0079  , p=0.9960  , df=2
parameter F test:         F=0.0039  , p=0.9961  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.0399  , p=0.9893  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=0.1225  , p=0.9890  , df=3
likelihood ratio test: chi2=0.1225  , p=0.9890  , df=3
parameter F test:         F=0.0399  , p=0.9893  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.9002  , p=0.4641  

C:\Users\HP\AppData\Local\Temp\ipykernel_8708\1911824464.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_jnj.colums = new_columns


{1: ({'ssr_ftest': (3.919021941960636, 0.04860734146169952, 317.0, 1),
   'ssr_chi2test': (3.95611047768897, 0.046701494929048966, 1),
   'lrtest': (3.93185578694613, 0.04737963241460901, 1),
   'params_ftest': (3.9190219419605943, 0.04860734146170273, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.0038965572242651452, 0.9961110726692602, 314.0, 2),
   'ssr_chi2test': (0.007917208627647014, 0.9960492206315404, 2),
   'lrtest': (0.007917110381299608, 0.9960492695606405, 2),
   'params_ftest': (0.0038965572242518984, 0.9961110726692602, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.03994526165023547, 0.989333139660778, 311.0, 3),
   'ssr_chi2test': (0.12253305342226573, 0.9890025991915037, 3),
   'lrtest': (0.12250945201753893, 0.9890056990971872, 3),
   'params_ftest': (0.039945261650255755, 0.9893331396607644, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
         

In [17]:
nvs_lly = [data_nvs['target'], data_lly['target']]
granger_lly = pd.concat(nvs_lly, axis=1)
columns=['NVS', 'JNJ']
granger_lly.colums = new_columns
grangercausalitytests(granger_lly, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=7.3639  , p=0.0070  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=7.4336  , p=0.0064  , df=1
likelihood ratio test: chi2=7.3486  , p=0.0067  , df=1
parameter F test:         F=7.3639  , p=0.0070  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.8796  , p=0.4160  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=1.7872  , p=0.4092  , df=2
likelihood ratio test: chi2=1.7822  , p=0.4102  , df=2
parameter F test:         F=0.8796  , p=0.4160  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.8978  , p=0.1299  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=5.8215  , p=0.1206  , df=3
likelihood ratio test: chi2=5.7689  , p=0.1234  , df=3
parameter F test:         F=1.8978  , p=0.1299  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=4.0804  , p=0.0031  

C:\Users\HP\AppData\Local\Temp\ipykernel_8708\3817913441.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_lly.colums = new_columns


{1: ({'ssr_ftest': (7.363902115204978, 0.007018527323329953, 317.0, 1),
   'ssr_chi2test': (7.433592040585467, 0.006401743005312546, 1),
   'lrtest': (7.348565224087679, 0.006711629815807975, 1),
   'params_ftest': (7.363902115205111, 0.0070185273233292185, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.8796091185125406, 0.4159649688247269, 314.0, 2),
   'ssr_chi2test': (1.787231266277073, 0.40917365318292165, 2),
   'lrtest': (1.7822433117926266, 0.41019539653481385, 2),
   'params_ftest': (0.8796091185126116, 0.4159649688247049, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (1.8977932867890501, 0.12988442869850125, 311.0, 3),
   'ssr_chi2test': (5.821526673944547, 0.1206236620546908, 3),
   'lrtest': (5.7688817705197835, 0.12341232484345599, 3),
   'params_ftest': (1.8977932867890683, 0.12988442869849784, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 

In [19]:
nvs_mrk = [data_nvs['target'], data_mrk['target']]
granger_mkr = pd.concat(nvs_mrk, axis=1)
columns=['NVS', 'MRK']
granger_mkr.colums = new_columns
grangercausalitytests(granger_mkr, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.3076  , p=0.5795  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=0.3105  , p=0.5774  , df=1
likelihood ratio test: chi2=0.3104  , p=0.5774  , df=1
parameter F test:         F=0.3076  , p=0.5795  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0602  , p=0.9416  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=0.1224  , p=0.9406  , df=2
likelihood ratio test: chi2=0.1224  , p=0.9407  , df=2
parameter F test:         F=0.0602  , p=0.9416  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.9714  , p=0.4065  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=2.9798  , p=0.3947  , df=3
likelihood ratio test: chi2=2.9659  , p=0.3969  , df=3
parameter F test:         F=0.9714  , p=0.4065  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.3250  , p=0.2605  

C:\Users\HP\AppData\Local\Temp\ipykernel_8708\1741930676.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_mkr.colums = new_columns


{1: ({'ssr_ftest': (0.30762021575298676, 0.5795353001422788, 317.0, 1),
   'ssr_chi2test': (0.3105314480787248, 0.577354250557498, 1),
   'lrtest': (0.3103808739517717, 0.5774465598842086, 1),
   'params_ftest': (0.3076202157530182, 0.5795353001422788, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.060228547509963176, 0.941560194748429, 314.0, 2),
   'ssr_chi2test': (0.1223752016285239, 0.9406467571248133, 2),
   'lrtest': (0.12235173476165073, 0.9406577942056767, 2),
   'params_ftest': (0.060228547509908324, 0.9415601947484454, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.971402684593823, 0.4064588661825803, 311.0, 3),
   'ssr_chi2test': (2.979801161101309, 0.3947499357040243, 3),
   'lrtest': (2.9659267369551117, 0.3969084927577441, 3),
   'params_ftest': (0.9714026845938643, 0.40645886618256366, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0

In [20]:
nvs_nvo = [data_nvs['target'], data_nvo['target']]
granger_nvo = pd.concat(nvs_nvo, axis=1)
columns=['NVS', 'NVO']
granger_nvo.colums = new_columns
grangercausalitytests(granger_nvo, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=6.3309  , p=0.0124  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=6.3908  , p=0.0115  , df=1
likelihood ratio test: chi2=6.3278  , p=0.0119  , df=1
parameter F test:         F=6.3309  , p=0.0124  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.6719  , p=0.0707  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=5.4289  , p=0.0662  , df=2
likelihood ratio test: chi2=5.3832  , p=0.0678  , df=2
parameter F test:         F=2.6719  , p=0.0707  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.8761  , p=0.1335  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=5.7549  , p=0.1242  , df=3
likelihood ratio test: chi2=5.7034  , p=0.1270  , df=3
parameter F test:         F=1.8761  , p=0.1335  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.8265  , p=0.1235  

C:\Users\HP\AppData\Local\Temp\ipykernel_8708\2682914152.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_nvo.colums = new_columns


{1: ({'ssr_ftest': (6.330873753726635, 0.012359027653305658, 317.0, 1),
   'ssr_chi2test': (6.390787385465373, 0.011471413318960452, 1),
   'lrtest': (6.327808632277765, 0.011885909406863333, 1),
   'params_ftest': (6.330873753726534, 0.012359027653306166, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (2.671891746055943, 0.07069285572167773, 314.0, 2),
   'ssr_chi2test': (5.428875585935322, 0.06624218436211363, 2),
   'lrtest': (5.383197662507428, 0.0677724959188541, 2),
   'params_ftest': (2.6718917460543277, 0.07069285572179042, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (1.8760691739127946, 0.13353655191922154, 311.0, 3),
   'ssr_chi2test': (5.754887433803235, 0.12416389213429543, 3),
   'lrtest': (5.703433807999545, 0.12696485633307922, 3),
   'params_ftest': (1.876069173912824, 0.13353655191921157, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0.,

In [21]:
nvs_pfe = [data_nvs['target'], data_pfe['target']]
granger_pfe = pd.concat(nvs_pfe, axis=1)
columns=['NVS', 'PFE']
granger_pfe.colums = new_columns
grangercausalitytests(granger_pfe, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.6327  , p=0.4269  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=0.6387  , p=0.4242  , df=1
likelihood ratio test: chi2=0.6381  , p=0.4244  , df=1
parameter F test:         F=0.6327  , p=0.4269  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.2050  , p=0.8148  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=0.4165  , p=0.8120  , df=2
likelihood ratio test: chi2=0.4162  , p=0.8121  , df=2
parameter F test:         F=0.2050  , p=0.8148  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.3429  , p=0.7943  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=1.0519  , p=0.7887  , df=3
likelihood ratio test: chi2=1.0502  , p=0.7891  , df=3
parameter F test:         F=0.3429  , p=0.7943  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.1151  , p=0.0788  

C:\Users\HP\AppData\Local\Temp\ipykernel_8708\1091317770.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_pfe.colums = new_columns


{1: ({'ssr_ftest': (0.632741440418527, 0.42694671931414585, 317.0, 1),
   'ssr_chi2test': (0.6387295297600272, 0.42417122757911807, 1),
   'lrtest': (0.6380929151721375, 0.42440222502668334, 1),
   'params_ftest': (0.6327414404184999, 0.42694671931414585, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.2049688525067189, 0.8147816042221163, 314.0, 2),
   'ssr_chi2test': (0.41646537547543516, 0.8120180680802025, 2),
   'lrtest': (0.41619375698155636, 0.8121283551313608, 2),
   'params_ftest': (0.20496885250665978, 0.814781604222159, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.3429214919673652, 0.7943041775029409, 311.0, 3),
   'ssr_chi2test': (1.0519199464207922, 0.7886916004293995, 3),
   'lrtest': (1.0501839379494413, 0.7891113989864448, 3),
   'params_ftest': (0.342921491967374, 0.7943041775029409, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 

In [22]:
nvs_rog = [data_nvs['target'], data_rog['target']]
granger_rog = pd.concat(nvs_rog, axis=1)
columns=['NVS', 'ROG']
granger_rog.colums = new_columns
grangercausalitytests(granger_rog, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0001  , p=0.9941  , df_denom=317, df_num=1
ssr based chi2 test:   chi2=0.0001  , p=0.9941  , df=1
likelihood ratio test: chi2=0.0001  , p=0.9941  , df=1
parameter F test:         F=0.0001  , p=0.9941  , df_denom=317, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.9052  , p=0.4055  , df_denom=314, df_num=2
ssr based chi2 test:   chi2=1.8392  , p=0.3987  , df=2
likelihood ratio test: chi2=1.8339  , p=0.3997  , df=2
parameter F test:         F=0.9052  , p=0.4055  , df_denom=314, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.6787  , p=0.5656  , df_denom=311, df_num=3
ssr based chi2 test:   chi2=2.0820  , p=0.5556  , df=3
likelihood ratio test: chi2=2.0752  , p=0.5569  , df=3
parameter F test:         F=0.6787  , p=0.5656  , df_denom=311, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.1729  , p=0.3227  

C:\Users\HP\AppData\Local\Temp\ipykernel_8708\3048451869.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  granger_rog.colums = new_columns


{1: ({'ssr_ftest': (5.475071231827073e-05, 0.994100863167208, 317.0, 1),
   'ssr_chi2test': (5.526885786071493e-05, 0.9940683392289754, 1),
   'lrtest': (5.5268853088819014e-05, 0.9940683394850396, 1),
   'params_ftest': (5.475071226311525e-05, 0.994100863171, 317.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.9051645394735944, 0.4055280568819404, 314.0, 2),
   'ssr_chi2test': (1.8391559751087683, 0.39868725657168474, 2),
   'lrtest': (1.833874549169309, 0.3997414665012808, 2),
   'params_ftest': (0.9051645394734531, 0.40552805688199733, 314.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.6787181171710542, 0.5656321601200172, 311.0, 3),
   'ssr_chi2test': (2.081984192222462, 0.55556607366562, 3),
   'lrtest': (2.07519829456578, 0.5569465899186816, 3),
   'params_ftest': (0.6787181171710991, 0.5656321601199888, 311.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 

In [23]:
start = "2022-01-01"
end = "2023-05-01"
t = ['NVS', 'JNJ', 'LLY', 'NVO']

deep_ar_2 = get_data(t, start, end)
deep_ar_2

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


ticker       close   close_lag    return   volume        high  \
Date                                                                       
2022-01-10    NVS   82.859161   82.150887  0.862163  2753400   90.129997   
2022-01-11    NVS   82.665993   82.859161 -0.233129  2104100   89.959999   
2022-01-12    NVS   82.592415   82.665993 -0.089006  2205100   89.849998   
2022-01-13    NVS   83.355881   82.592415  0.924378  1864600   90.989998   
2022-01-14    NVS   83.291489   83.355881 -0.077250  1576200   90.860001   
...           ...         ...         ...       ...      ...         ...   
2023-04-24    NVO  170.479996  172.649994 -1.256877  1188200  171.419998   
2023-04-25    NVO  168.580002  170.479996 -1.114497  1117300  170.869995   
2023-04-26    NVO  164.990005  168.580002 -2.129551  1121400  165.770004   
2023-04-27    NVO  166.020004  164.990005  0.624279  1153800  166.240005   
2023-04-28    NVO  167.089996  166.020004  0.644496  1118800  168.089996   

                   low  rolling_var_5     target  
Date                                              
2022-01-10   88.459999      -0.305103  -1.883557  
2022-01-11   89.290001      -0.127432  -1.555772  
2022-01-12   89.169998      -0.204304  -1.359631  
2022-01-13   90.120003      -0.204304  -1.183775  
2022-01-14   90.139999      -0.204304  -1.045448  
...                ...            ...        ...  
2023-04-24  169.729996      -2.489566 -10.145321  
2023-04-25  168.199997      -2.489566 -12.146153  
2023-04-26  163.470001      -1.955016 -11.712162  
2023-04-27  164.449997      -1.955016 -11.278171  
2023-04-28  165.570007      -1.955016 -10.844180  

[1308 rows x 9 columns]

In [24]:
deep_ar_2.to_csv("dar_data2.csv")